### ISSUE TITLE
Clarify tool use code execution safety

### ISSUE THREAD

**Issue by justinwiley** [Doriandarko/claude-engineer#107]
Interesting project, thanks for sharing.  While reading through the README I noticed:

"Claude Engineer now supports executing code in an isolated virtual environment: Use the execute_code tool to run Python code safely."

I think it would be useful to clarify that you're creating a python virtual environment using venv, not in a virtual machine which I think would be a common assumption.  The venv only offers limited package isolation and does nothing to prevent claude from going off the rails and executing dangerous code.

Similarly, the execute_code tool uses a subprocess, which runs as the user who launched (likely a privileged user) and does nothing to prevent malicious python from being implemented.

So AFAICT there is no safe code execution model present here, and I think folks should be aware that they are taking on some risk allowing an LLM to execute arbitrary python on their machine without guardrails.

Consider reimplementing with something like PyPy's sandbox: https://doc.pypy.org/en/latest/sandbox.html

**Comment by Doriandarko** [comment]
Good point!

**Comment by awesomebytes** [comment]
Hello @Doriandarko , I know this one has been closed, but I would propose to execute everything inside of a Docker container as a future thing.
This would apply for any language, with fine-grained control of permissions in the environment (only show certain files, libraries, sockets, devices, etc).

And thanks for sharing your cool work!

**Comment by mrharrison007** [comment]
Has anyone tried to dockerize claude-engineer yet?
