### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by haesleinhuepf** [Doriandarko/claude-engineer#116]
Hi @Doriandarko ,

amazing project, congratulations! Just a minor request: in the readme it mentions the work is licensed MIT and a license file. However, the file is missing in the repository. It would be great to add it for clarity under which conditions this work can be reused.

Thanks!

Best,
Robert

**Comment by seoplanotx** [comment]
https://memgraph.com/blog/what-is-mit-license

**Comment by seoplanotx** [comment]
> Hi @Doriandarko ,
> 
> amazing project, congratulations! Just a minor request: in the readme it mentions the work is licensed MIT and a license file. However, the file is missing in the repository. It would be great to add it for clarity under which conditions this work can be reused.
> 
> Thanks!
> 
> Best, Robert

https://memgraph.com/blog/what-is-mit-license

**Comment by hargup** [comment]
@Doriandarko now the README doesn't mention any license, having a license will encourage contributions, thanks :)
