### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by alioop222** [Doriandarko/claude-engineer#132]
Hi @Doriandarko please forgive my ignorance. I am a beginner, but how do i get updates to the code? Since i started using claude engineer i havent pushed any commits because im building on your claude engineer, im adding a desktop gui, but i remember reading in the docs that we should discuss additions with you before doing anything. Could you enlighten me about how to proceed. Firstly how to get the update you posted. Do i just copy and paste the code into the respective files or is there an update button i can press?

**Comment by ovachiever** [comment]
First, no GUI! haha

Second, fork the repo which will make a point in time copy of the original repo and then run git locally and then set your forked repo as the upstream repo to be tracked, call it something like upstream.

Then your changes will stay yours and you can pull updates from the main repo by adding the original repo as another remote, call it something like origin, and then fetch and merge those changes, bringing new updates into your forked repo.

**Comment by alioop222** [comment]
Hi @ovachiever Thanks i‘ll remember that. Im just going through my huge mess of commits with claude, we’re getting there! The updates on this repo - did he make it interchangeable for models? I’d like to plug a local ollama model in this to test it against sonnet 3.5.

**Comment by ovachiever** [comment]
I believe he's working that, based off what I've read on X. I have it going through OpenRouter now via an optional API menu, and while it works, tool usage breaks because OR uses the OpenAI client schema. Running into a skill issue here trying to normalize (or de-normalize since OR does this) and get it working regardless of the API endpoint.
