### ISSUE TITLE
Feature request: Comparing results against other models?

### ISSUE THREAD

**Issue by aronchick** [Doriandarko/claude-engineer#137]
It'd be interesting to have an agent that could contact other endpoints as a way to vet the results of Claude-engineer. Especially with the advancements of GPT4o and llama-405B!

**Comment by tyfong-lbl** [comment]
I am trying to use the tool to edit itself so that it will support any OpenAI type endpoint. I have forked the code and will try to push this to my own repo later today.

**Comment by tyfong-lbl** [comment]
@aronchick I've uploaded my fork here: https://github.com/tyfong-lbl/claude-engineer-multipoint/tree/update-to-openai-endpoint

It doesn't work at the moment -- I think it has to do with the tools call in the chat completion.
