### ISSUE TITLE
Support Amazon Bedrock to raise rate limits

### ISSUE THREAD

**Issue by philikai** [Doriandarko/claude-engineer#141]
Through Amazon Bedrock the default quotas for Anthropic Claude 3.5 are considerably higher than through anthropic directly.

**Comment by mcauthorn** [comment]
[Have a look here for an updated main.py with support](https://github.com/Doriandarko/claude-engineer/blob/937e7f502c05af0ff1aeb2b6601b8d578abcce49/main.py
)

Looks like you'll need to add a `USE_AWS_BEDROCK=true` to your .env file.

**Comment by renebrandel** [comment]
Hi folks - I cut a PR to support Amazon Bedrock directly if no Anthropic API Key is present: https://github.com/Doriandarko/claude-engineer/pull/153
