### ISSUE TITLE
Adding tags for repo

### ISSUE THREAD

**Issue by vasnt** [Doriandarko/claude-engineer#151]
![image](https://github.com/user-attachments/assets/22b6247b-9d7f-4e4e-9190-4655b9e618c3)

- Tagging/labelling (e.g. as above) may help during TOPICS search 
e.g. https://github.com/topics/agent

**Comment by 573dave** [comment]
https://github.com/Doriandarko/claude-engineer About> Topics> (copy and paste)
anthropic claude-ai ai llm python chain-of-thought prompt-engineering instruction-tuning
