### ISSUE TITLE
API Error: model "mistral-nemo" not found, try pulling it first     

### ISSUE THREAD

**Issue by abonetee** [Doriandarko/claude-engineer#158]
After i have ran  python3 ollama-eng.py, i then see ollama -engineer active, but then once i ask the LLM a question i get "API Error: model "mistral-nemo" not found, try pulling it first  " error.

i even had to go and get an API key from Mistral Nemo, do i need to create another .env file and put the API key in there ?
<img width="623" alt="Screenshot 2024-08-03 at 2 14 18 PM" src="https://github.com/user-attachments/assets/ce73c08f-2485-4602-8a33-02e6b51b77bd">

**Comment by danieldunderfelt** [comment]
You need to install Ollama, then run "ollama pull mistral-nemo" in your terminal.

**Comment by abonetee** [comment]
I eventually did so after I went and researched a lot of YouTube videos ,
the other issue I started facing was when I run that Ollama - engineer in
my local LLM it doesn’t use the tools like Claude-engineer would, is the
there a tweak to this ?
