### ISSUE TITLE
Overload issue Error code:529

### ISSUE THREAD

**Issue by BBalint21** [Doriandarko/claude-engineer#161]
Hi guys! I have used claude engineer for around 2 weeks now, and today I got this error code every time I try to talk to it: "API Error: Error code: 529 - {'type': 'error', 'error': {'type': 'overloaded_error', 'message': 'Overloaded'}}"

Is the problem on my end or can it be just Claude? I have money added to my Anthropic balance so the API should work.

Thanks in advance!

**Comment by ap24fl** [comment]
+1

**Comment by arminta7** [comment]
+1

**Comment by janacm** [comment]
From Anthropic:

Error events
We may occasionally send [errors](https://docs.anthropic.com/en/api/errors) in the event stream. For example, during periods of high usage, you may receive an overloaded_error, which would normally correspond to an HTTP 529 in a non-streaming context:

See: https://docs.anthropic.com/en/api/messages-streaming

**Comment by fatherofinvention** [comment]
It’s crazy how much this happens. Basically if you see Claude defaulting to “concise responses “ then you know the API is down too. Huge bummer to be the ones with the frontier models but bad infra.
