### ISSUE TITLE
Claude Engineer works for very small projects, but not for big ones

### ISSUE THREAD

**Issue by xavitg** [Doriandarko/claude-engineer#162]
Hello,

After trying Claude Engineer and Claude-Dev, Claude Engineer seems to work only with small projects. Let me explain why:

With Claude-Dev you can edit a 5,000 lines of code file without any problem. It's amazing. With Claude Engineer, Claude is all the time rewriting the complete file again and again, consuming an insane amount of tokens and of course failing when the file is more than 1000 lines long, because it tries to rewrite the whole thing.

I spent like $500 with Claude Engineer (Claude API) trying to resolve some normal issues and it fails all the time, since the code files are longer than 1,000 lines... the result was horrible. Spent 500 usd for nothing, because claude engineer cannot repair the problems because it tries to rewrite all the code over and over.
And with Claude Dev, the tokens consumption is 10000 times less.

Claude Engineer, should work as Claude-Dev. If I ask to fix for a specific issue on my app, it should go to the proper file and edit just specific lines, not the whole file.

**Comment by m-marinucci** [comment]
Similar experience agree!

**Comment by xavitg** [comment]
> Similar experience agree!

The creator of Claude Engineer doesnt reply any issue. He created also another project. He just abandoned the project. If you wanna work with a powerful tool use Aider or Claude Dev, x1000 better than Claude Engineer.

**Comment by htelsiz** [comment]
> > Similar experience agree!
> 
> The creator of Claude Engineer doesnt reply any issue. He created also another project. He just abandoned the project. If you wanna work with a powerful tool use Aider or Claude Dev, x1000 better than Claude Engineer.

That's pretty rude.

**Comment by m-marinucci** [comment]
> > > Similar experience agree!
> > 
> > 
> > The creator of Claude Engineer doesnt reply any issue. He created also another project. He just abandoned the project. If you wanna work with a powerful tool use Aider or Claude Dev, x1000 better than Claude Engineer.
> 
> That's pretty rude.

I agree nobody deserves such negative comment! Respect for the authors!

**Comment by HarryBak** [comment]
> > Similar experience agree!
> 
> The creator of Claude Engineer doesnt reply any issue. He created also another project. He just abandoned the project. If you wanna work with a powerful tool use Aider or Claude Dev, x1000 better than Claude Engineer.

You could try putting in a pull request to fix the issues you are facing to try and propel the project forward.

**Comment by jean-moorman** [comment]
its true that claude-engineer does this sometimes but you can also just ask it to make the specific edits with the edit command instead of recreating the file from scratch
