### ISSUE TITLE
Version issue with Tavily 0.3.6 or 0.3.7: needs to be 0.3.5

### ISSUE THREAD

**Issue by edmondtam1** [Doriandarko/claude-engineer#163]
Hi folks,

I just came across this repo and while doing a fresh install, I found a bunch of packages missing from Tavily. Downgrading to `tavily-python==0.3.5` helped fix it.

Just letting others know!

**Comment by raghavan** [comment]
Thanks for your post. It really helped to resolve some dependency issues.
