### ISSUE TITLE
Anthropic API compatibility issue

### ISSUE THREAD

**Issue by m-marinucci** [Doriandarko/claude-engineer#164]
Hello 
 it appears that there's a compatibility issue between the version of the Anthropic Python library being used and the code in the script. The error suggests that the Anthropic client object doesn't have a messages attribute, which is likely due to changes in the library's API. The code is trying to use client.messages.create(), which is a newer API format. However, in the requirements.txt the installed version of the Anthropic library doesn't support this format.

I tried pip install --upgrade anthropic to consider the most recent version and worked. Please consider 
pip show anthropic command you should get . 
Name: anthropic
Version: 0.33.0

if you have a lower version it won't work

**Comment by dazzafact7** [comment]
I have a similar problem: the module "Anthropic" does not seem to be imported, although it was definitely installed (py 3.10)

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from anthropic import Anthropic, APIStatusError, APIError
ModuleNotFoundError: No module named 'anthropic'
```
![image](https://github.com/user-attachments/assets/7f164bfe-5421-4248-a48f-c4edc71d1244)

![image](https://github.com/user-attachments/assets/f977f4d2-0ccd-40c3-b738-f96de04f82fe)
