### ISSUE TITLE
roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'

### ISSUE THREAD

**Issue by lgiavedoni** [Doriandarko/claude-engineer#18]
You: automode
Entering automode. Please provide your request.

You: create a web ecommerce store with home and PLP
Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I'm sorry, there was an error communicating with the AI. Please try again.
Continuation iteration 1 completed.
Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I'm sorry, there was an error communicating with the AI. Please try again.
Continuation iteration 2 completed.
Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I'm sorry, there was an error communicating with the AI. Please try again.
Continuation iteration 3 completed.
Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}

**Comment by lgiavedoni** [comment]
sorry, seems to be working now. Thanks

**Comment by Doriandarko** [comment]
Update your anthropic package too!
