### ISSUE TITLE
Voice is working (?)

### ISSUE THREAD

**Issue by AndySharez** [Doriandarko/claude-engineer#187]
Hi, so I tried to use the voice feature.
I cannot get it to work.

Surely I have an api key for tavily,
but no matter whether I type _11labs on_ or _voice_, engineer does not understand it (thinks it is a random word, not a command).

I have updated before as well.

Has anyone else tried the voice feature?

**Comment by Doriandarko** [comment]
It works. Type voice to use your voice to talk to the model, and 11labs on if you want to use 11labs for text to speech. If you want to use your voice and 11 labs at the same time, first activate 11labs then type voice to use your voice.

**Comment by AndySharez** [comment]
Thanks, will try it again.
Great product 👍
