### ISSUE TITLE
the costs of using claude with this are exploding.. 1$ per prompt after a while

### ISSUE THREAD

**Issue by MaximPro** [Doriandarko/claude-engineer#190]
I don't know, whats wrong here, but compared to other tools, the costs are higher then I thought.
I spend 200$ in the last 2 days, using aftermode a few times... but this seems pretty high, especially compared to chatgpt.
And what about caching etc?
Also it couldn't resolve basic issues and jumped around and around.
Also I have a suspision, anthropic dumbed claude3,5 sonnet down, in the sense of its jumping around and suggest strange or unneccesary ideas to leech more api credits.... I watched it basically do that.. but iam not 100% sure.

However Claude Engeneer sadly seems not to be ready yet... for production building.

**Comment by erosborba** [comment]
I can't use it anymore; it's just not feasible. Every request hits the API limit, and I’ve spent 6 dollars in credits to generate just 27KB of React code. It doesn’t make sense — 27KB is about 27,000 characters, and the token limit per minute is 40,000 (took me more then 10 minutes to do 27kb). It seems like a large portion of the tokens are being consumed by the agents' prompts, but I’m not sure.

**Comment by devoidiaGamble** [comment]
Yep its insane.   rate limits hit and cost through the roof.   Trying to figure out a way to just run locally.

**Comment by jean-moorman** [comment]
the problem is that the tool checker model, despite supposedly not saving context, actually uses the full conversation history, so it ends up exponentially consuming resources

**Comment by PierrunoYT** [comment]
Pls add OpenRouter
