### ISSUE TITLE
Files and folder structure get confused.

### ISSUE THREAD

**Issue by brianlmerritt** [Doriandarko/claude-engineer#193]
After the prompt below, claude-engineer thought it had created the file directory structure but nothing was there.  When I asked (second prompt), it created the files in a subfolder called "LANGCHAIN_RAG"

`Create a LangChain LLM RAG with semantic chunking and agentic reranking to a Weiviate vector store on the usual port.  Core functions are segment_text, update_segmented_text (where an existing document has been updated) and search_best_results (perform retrieval functions)`

No files were created so I typed `I don't see any files here`

A LANGCHAIN_RAG directory was created, files created, but from that point commands might do things like overwrite the parent directory (.env file was trashed).

Should I spell out the project directory in the first command so files and folders are set up properly?  It couldn't find the files when I closed the terminal and reopened.

(Note: This also raises the question of doing multiple projects - do I have to clone one copy per project?)

This project is awesome!  Will be trying the openai one as well and see how they copy with the same input.

**Comment by nsdevaraj** [comment]
https://aider.chat try this

**Comment by brianlmerritt** [comment]
I think where I went wrong was in starting in auto mode. /create makes a perfectly good project base.  I was interested in getting @Doriandarko feedback if time permits.

**Comment by brianlmerritt** [comment]
Closing this ticket as I believe starting the project with /create is better and then can use automode later if needed.
