### ISSUE TITLE
unexpected keyword argument 'tools'

### ISSUE THREAD

**Issue by Precognist** [Doriandarko/claude-engineer#23]
I got this error:

Error calling Claude API: Messages.create() got an unexpected keyword argument 'tools'
I'm sorry, there was an error communicating with the AI. Please try again.

Tried using **kwargs and *args to solve. Not working.

**Comment by RonPare** [comment]
Error calling Claude API: Messages.create() got an unexpected keyword argument 'tools'
I'm sorry, there was an error communicating with the AI. Please try again.

**Comment by superhero75** [comment]
Same problem

**Comment by kieranklaassen** [comment]
Same here: 

```
Error calling Claude API: Messages.create() got an unexpected keyword argument 'tools'
I'm sorry, there was an error communicating with the AI. Please try again.```

**Comment by Doriandarko** [comment]
Make sure you update to the latest Anthropic package

**Comment by jasonkneen** [comment]
same and have latest, on paid plan
