### ISSUE TITLE
Getting auth error running it

### ISSUE THREAD

**Issue by gordingin** [Doriandarko/claude-engineer#29]
Just saw the youtube video. So I downloaded it. I got both APIs keys and added it. I tried a CURL sample from anthropic and using the key IT generated, it did work. 

What am I missing?

Claude API: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}

**Comment by gordingin** [comment]
Odd, it just started to work. Thanks!

**Comment by jamesw6811** [comment]
I'm now getting this same error. new setup, used .env example.
