### ISSUE TITLE
Double responses?

### ISSUE THREAD

**Issue by roblineker** [Doriandarko/claude-engineer#35]
I am receiving double responses from the claude-engineer. What would be causing this?

Claude: I apologize, but I don't have any prior context or memory of what we were doing before. Each conversation with me starts fresh, and I don't retain information from previous interactions. Could you please provide more details about what you're referring to or what you'd like assistance with? I'd be happy to help if you can give me some more information about your current task or question.
I apologize, but I don't have any prior context or memory of what we were doing before. Each conversation with me starts fresh, and I don't retain information from previous interactions. Could you please provide more details about what you're referring to or what you'd like assistance with? I'd be happy to help if you can give me some more information about your current task or question.

**Comment by AlexJ-StL** [comment]
You're not the only one. I too start started a thread about this yesterday. https://github.com/Doriandarko/claude-engineer/issues/34#issue-2384550546

**Comment by roblineker** [comment]
Thanks @AlexJ-StL I'll close this one then. Hopefully gets resolved asap.
