### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by Mars-2030** [Doriandarko/claude-engineer#46]
Hi how can I save this error? 

<img width="1039" alt="image" src="https://github.com/Doriandarko/claude-engineer/assets/68222677/4e3d431f-7b2f-47f0-92c3-a81eabb70ce6">

**Comment by Oconemy** [comment]
Had this a couple times, restarting main.py worked for me

**Comment by Doriandarko** [comment]
This is fixed in the latest version now
