### ISSUE TITLE
Error calling Claude API

### ISSUE THREAD

**Issue by pat3dx** [Doriandarko/claude-engineer#49]
Here is the issue in automode:

Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.126: all messages must have non-empty content except for the optional final assistant message'}}
I'm sorry, there was an error communicating with the AI. Please try again.

**Comment by Doriandarko** [comment]
I can’t replicate it. Do you remember what you did to tiger the error?

**Comment by pat3dx** [comment]
I had just launched the automode, iteration 100 and indicated my project to the AI. There were several steps for the creation of my project and for several of them. I had the error. So, Claude went to the next step when there was the error. So, there were a lot of things missing in my project, at the end of the automode.

**Comment by gmb9000** [comment]
Same problem. This first happened in automode after about 8 iterations, then manual iterations. 

1. First, let's check the contents of your package.json file to ensure the start script is correctly defined:
I encountered an error while processing the tool result. Please try again.

You: Error calling Claude API: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': 'Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.'}}
I'm sorry, there was an error communicating with the AI. Please try again.

You: Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.104: all messages must have non-empty content except for the optional final assistant message'}}
I'm sorry, there was an error communicating with the AI. Please try again.

You: Error calling Claude API: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': 'Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.'}}
I'm sorry, there was an error communicating with the AI. Please try again.

**Comment by Doriandarko** [comment]
This should be fixed now

**Comment by gmb9000** [comment]
1. With automode if I enter my number of iterations [10], it says 25 regardless of the number. i.e. automode [10]
2. without automode I've been running into rate limits again. I get the pause, and retries, but still hit the limits. It interrupts the response "You: sers/projects/my-project/no╭────────────────────────────────────── API Error ───────────────────────────────────────╮
│ Rate limit exceeded. Retrying after a short delay...                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────── API Error ───────────────────────────────────────╮
│ Rate limit exceeded. Retrying after a short delay...                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────── API Error ───────────────────────────────────────╮
│ Rate limit exceeded. Retrying after a short delay...                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────── API Error ───────────────────────────────────────╮
│ Rate limit exceeded. Retrying after a short delay...                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Claude's Response ────────────────────────────────────────────────────────────────────╮
│ Thank you for providing that additional context. The caret (^) in the error message is

You: de_modules╭────────────────────────────────────── API Error ───────────────────────────────────────╮
│ Rate limit exceeded. Retrying after a short delay...                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────── API Error ───────────────────────────────────────╮
│ Rate limit exceeded. Retrying after a short delay...                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by Doriandarko** [comment]
is without the bracket sorry, just the number
