### ISSUE TITLE
Unable to view images

### ISSUE THREAD

**Issue by gmb9000** [Doriandarko/claude-engineer#53]
Typed image and dragged the file into terminal. Tried again by copying and pasting the file path:

"I apologize, but I'm unable to directly access or view images stored on your local machine. As an AI language model, I don't have the capability to access external files or images unless they are explicitly provided in the conversation."

**Comment by Doriandarko** [comment]
Type image, drag the file then press enter. Don’t type any message

_________________________
*Pietro Schirano*
Founder | EverArt <http://everart.ai>
