### ISSUE TITLE
TypeError: Messages.create() got an unexpected keyword argument 'tools'

### ISSUE THREAD

**Issue by Minocrisy** [Doriandarko/claude-engineer#67]
This is probably me, but I re-cloned the latest repo and now any input results in this error.
(I have also created a new directory and relocated files, but this was happening before. So i deleted everything and started again in the new location)

![Capture](https://github.com/Doriandarko/claude-engineer/assets/141797927/58b5b9c8-5b7b-4b6e-98df-5f13e4573f94)

**Comment by Doriandarko** [comment]
I can’t seem to reproduce this. Can you try downloading the repo again and running the script?

**Comment by jthack** [comment]
i got the same error @Doriandarko. all i did was follow the install instructions @Doriandarko

**Comment by jthack** [comment]
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/4ed41d2c-c3d3-4ea3-87e4-44fdc9bf56d8">

**Comment by jthack** [comment]
yeah, this is a legit issue with latest `anthropic`

**Comment by jasonkneen** [comment]
aha!

**Comment by jasonkneen** [comment]
Dammit, same issue
