### ISSUE TITLE
Claude Engineer became acustic

### ISSUE THREAD

**Issue by heewxmf** [Doriandarko/claude-engineer#71]
Almost any action it attempts, ends up in failure...
![image](https://github.com/user-attachments/assets/1cf6bc7d-c3b5-4d67-97bc-ad1ed8f1dc79)
![image](https://github.com/user-attachments/assets/404147c0-b635-4e53-b94f-d8413a5250da)
![image](https://github.com/user-attachments/assets/74f7c78e-7d2f-45c7-8232-4080d4c0d408)

It all started when it was unable to read the file because of encoding? so I fixed that read_file function to include encoding="UTF-8"
so it read the file fine, but now it's unable to do anything... did it became acoustic? was it nerfed?

**Comment by Doriandarko** [comment]
This is an issue with editing of long files. Was the file you were editing really long? BTW, a fix for this is on its way.

**Comment by heewxmf** [comment]
yeah I think it was pretty long, tho then I attempted to make it actually create a new file which was empty and got the same issue..

**Comment by NataliaHaronitou** [comment]
That happened to me as well and I had to go back to the previous version of claude engineer

**Comment by Doriandarko** [comment]
> yeah I think it was pretty long, tho then I attempted to make it actually create a new file which was empty and got the same issue..

A new version is dropping tomorrow which will solve long file editing.
