### ISSUE TITLE
Improve process for generating and integrating large codebases with Claude

### ISSUE THREAD

**Issue by rashlab** [Doriandarko/claude-engineer#73]
This issue addresses the limitations of Claude's code generation capabilities for large files and proposes solutions to improve the process.

Claude's output is limited to 4096 tokens. Considering text that is added to the code output, this means that Claude is very limited in its ability to output complete files which are longer than 250 lines, and instead Claude tends to return partial, incomplete files, with comments like "// ... rest of the file remains unchanged". 

When users try to combine or integrate these partial outputs into a complete codebase, they often encounter errors or issues due to inconsistencies between different parts of the code generated in separate responses, missing context or dependencies when code is generated in isolation and human error in the process of combining these partial outputs. For me, the diff feature did not solve the issue.

In my attempts to address the issue, I use two methods that I found to be useful and I'm now happy to share them. 
First, I use line numbers. I do that by adding line numbers in the read_files tool, and requiring Claude to include those line numbers in its output (both in the files he provides and in the explanations). 
Here are the relevant lines (btw note the encoding="utf-8" which is important sometimes):
```python
# adding line numbers in read_files tool
with open(path, "r", encoding="utf-8") as f:
    file_content = f.read()
    lines = file_content.splitlines()
    # Add line numbers and format the content
    numbered_lines = [f"{i+1:4d}  {line}" for i, line in enumerate(lines)]
    ...
```
 
This little trick is helpful, but far from enough. What really was a game changer for me was the next trick, which is to split my project files to code sections of up to 200 lines each. For example, if my python file is 700 lines, I split the same file to 4 sections by including commented \<SECTION\> tags in the file:
```python
# <SECTION 1>
# .... code for section 1... (lines 2- 180)
# </SECTION 1>
# <SECTION 2>
# .... code for section 2... (lines 184- 350)
# </SECTION 2>
etc...
```

Then I require Claude to provide full code sections, a single section in each file it saves using the create_file tool. I don't give him the option to use write_to_file or edit_and_apply tools, but only the 'create_file' tool. 
I found that this makes the integration of the changes made by Claude much easier and less error prone. 
To make it work well, I'm shameful to admit that I needed to kind of "threaten" Claude that if it will not respect these rules I will reject and ignore his work. This is the suffix I append to any prompt before the call to chat_with_claude :
"""
REMEMBER! \n --- before starting to work on your task it's important that you will read again and follow your Rules of Conduct.\n
If you do not include the full content of code sections in the file you create - your work will be rejected and ignored! \n
If you include comments in the file like "// ... rest of the file remains unchanged" - your work will be rejected and ignored! \n
If you include more than a single code section in a single file - your work will be rejected and ignored! \n 
Please just follow the Rules of Conduct, and we will be happy with your work.
"""

Hope you all find it useful, and cheers to Pietro - great work!

**Comment by Doriandarko** [comment]
So I tried this, but it actually doesn’t work well. It could either break the code, add duplicates, or edit the wrong line. I do have a fix for this that I have been working on. It’s very promising. I'll test it a bit more, then I’ll share it.

**Comment by rashlab** [comment]
Great! I'll be happy to have a better solution for this, this is a critical usability issue in my view. 
Meantime this is working perfectly for me. In addition to the suffix I provide in each call, I added the following to the system prompt (among some other 'Rules of Conduct'):
```python
"""
The project files are written mainly in Python, Javascript, CSS and HTML. 
The content in any project file is splitted into code sections. 
Small files (less than 200 lines) may have a single code section, while larger files may have two, three or even more code sections. 
The content of a code section is enclosed withing special commented tags as follows: \n
---
# <SECTION 1>
here comes the full content of section 1... 
# </SECTION 1>
# <SECTION 2>
here comes the full content of section 2...
# </SECTION 2>
...
---
Here is the most important rule for you: 
when you edit files, fixing bugs or adding new features, you must always create a new file that will contain the a full single code section, enclosed inside commented <SECTION> tags. 
You must never add more content to a single file, and you must include the FULL content of a single code section without any shortcuts or comments such as '\\ the remaining part is unchanged. 
To create the file use the 'create_file' tool, and name the file by it's original name followed by the respective section number. 
For example, if you modified code section #2 of the file 'app.js', you will create a new file named 'app_2.js', etc.\n
"""
```

**Comment by Doriandarko** [comment]
A new version dropping tomorrow that will fix this.
