### ISSUE TITLE
[Question] Do I have to install this per each project I want to use it on? Any way to install this once and use it in any given project directory?

### ISSUE THREAD

**Issue by dchuk** [Doriandarko/claude-engineer#75]
(preface: project looks amazing, good stuff) Ideally I'd like to install and use this like Aider, where it's installed once and then I can fire it up in any given project directory. Is this possible?

**Comment by seoplanotx** [comment]
You can, you just have to move your project DIR into the Claude-Engineer DIR and tell it the path

**Comment by Doriandarko** [comment]
> You can, you just have to move your project DIR into the Claude-Engineer DIR and tell it the path

Yes this is correct!
