### ISSUE TITLE
Maintain external state

### ISSUE THREAD

**Issue by aronchick** [Doriandarko/claude-engineer#76]
I’m having an issue where I quickly run out of tokens. This is fine, as I’m not in a rush, but it means the session dies and I have to recreate it later. Is there a way to capture state of the system - what was done, what is being worked on, etc. externally so that when I restart, we can recover most/all?

**Comment by prefonty** [comment]
+1

**Comment by aronchick** [comment]
@Doriandarko heya - do you mind if i write this in a pull request? my strategy will be to create a local sqlite database, and use that for conversation and state storage.

**Comment by Doriandarko** [comment]
A new version is dropping tomorrow which will allow to save chats.

**Comment by aronchick** [comment]
Terrific! Can’t wait :)

**Comment by aronchick** [comment]
Just FYI - I converted all my PRs to draft - if you have any feedback, i'm happy to change them over. I'm also happy to merge in anything I've done if you like it.
