### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\<'

### ISSUE THREAD

**Issue by parkertoddbrooks** [Doriandarko/claude-engineer#8]
I get this warning when running python3 main.py 

```
(venv) parker@PxB-MBP-16 claude-engineer % python3 main.py                
/Users/parker/claude-engineer/main.py:34: SyntaxWarning: invalid escape sequence '\<'
  system_prompt = """
```

**Comment by anibalinbalin** [comment]
Me too. 

`anibalin@Anibals-MacBook-Pro-M1 claude-engineer % python3 main.py

/Users/anibalin/Sites/anibal2/claude-engineer/main.py:34: SyntaxWarning: invalid escape sequence '\<'
  system_prompt = """
Traceback (most recent call last):
  File "/Users/anibalin/Sites/anibal2/claude-engineer/main.py", line 1, in <module>
    from anthropic import Anthropic
ModuleNotFoundError: No module named 'anthropic'
anibalin@Anibals-MacBook-Pro-M1 claude-engineer % `

The requirements seems to be ok too:
` pip install -r requirements.txt

Requirement already satisfied: anthropic in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.30.0)
Requirement already satisfied: colorama in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.18.0)
Requirement already satisfied: tavily-python in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.3.3)
Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (1.0.1)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (10.3.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (4.3.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (0.27.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (0.5.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (2.7.1)
Requirement already satisfied: sniffio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: tokenizers>=0.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (0.19.1)
Requirement already satisfied: typing-extensions<5,>=4.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anthropic->-r requirements.txt (line 1)) (4.11.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tavily-python->-r requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: tiktoken<1,>=0.5.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tavily-python->-r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: idna>=2.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from anyio<5,>=3.5.0->anthropic->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx<1,>=0.23.0->anthropic->-r requirements.txt (line 1)) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpx<1,>=0.23.0->anthropic->-r requirements.txt (line 1)) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->anthropic->-r requirements.txt (line 1)) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->anthropic->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->anthropic->-r requirements.txt (line 1)) (2.18.2)
Requirement already satisfied: regex>=2022.1.18 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tiktoken<1,>=0.5.2->tavily-python->-r requirements.txt (line 4)) (2024.5.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->tavily-python->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->tavily-python->-r requirements.txt (line 4)) (2.2.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tokenizers>=0.13.0->anthropic->-r requirements.txt (line 1)) (0.23.0)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.0->anthropic->-r requirements.txt (line 1)) (3.14.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.0->anthropic->-r requirements.txt (line 1)) (2024.5.0)
Requirement already satisfied: packaging>=20.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.0->anthropic->-r requirements.txt (line 1)) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.0->anthropic->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: tqdm>=4.42.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.0->anthropic->-r requirements.txt (line 1)) (4.66.4)
`

**Comment by PierrunoYT** [comment]
Same here

**Comment by parkertoddbrooks** [comment]
This is fixed in: https://github.com/Doriandarko/claude-engineer/commit/235bd2a9d5f11705330214195ff3bbef0da62dd8
