### ISSUE TITLE
readme.md - fix 'yourusername' in instructions

### ISSUE THREAD

**Issue by anonymort** [Doriandarko/claude-engineer#87]
The instructions incorrectly show 'yourusername' rather than 'Doriandarko'.

![image](https://github.com/user-attachments/assets/c44d430c-bc1f-47c6-8c8c-21f14904b5a3)

**Comment by Doriandarko** [comment]
Good catch

**Comment by ggoosen** [comment]
This is what happens when you use claude engineer to write claude engineer ;)
