### ISSUE TITLE
Assistant position

### ISSUE THREAD

**Issue by vefjun** [Doriandarko/claude-engineer#9]
Hello and thanks for a great tool. When using the newest version I get this:
You: Error calling Claude API: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'Your API request included an `assistant` message in the final position, which would pre-fill the `assistant` response. When using tools, pre-filling the `assistant` response is not supported.'}}

**Comment by Doriandarko** [comment]
This is fixed

**Comment by ai212983** [comment]
Not sure how this fix should work, I am seeing this error right now, repo was checked out 5 minutes ago.
