### ISSUE TITLE
Idea: git commit after every change

### ISSUE THREAD

**Issue by matheusd** [Doriandarko/claude-engineer#92]
Would be useful to track the changes the model has done. The history could be used in the future to train new models (very speculative idea).

Ideally, this tracking over git would work on a separate repository to the main project (so, if I'm working on some project `alpha`, with its main git repository, the changes that the model are performing would be stored on a separate git repository.

Or maybe on a separate branch. I'm rambling here.

**Comment by dchuk** [comment]
Seems like a simple implementation of a gitflow model, where each new request to claude-engineer starts a feature branch, and then commits are made to that branch on each iteration, would be ideal. No need for a separate repo, that would get confusing.

**Comment by Doriandarko** [comment]
Considering this
